# Generated by Django 5.2.16 on 2026-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nearest_station', models.CharField(max_length=100)),
                ('has_car', models.BooleanField(default=False)),
                ('car_capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
