# Generated by Django 5.2.16 on 2026-07-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('gather_station', models.CharField(max_length=100)),
                ('gather_time', models.TimeField()),
                ('members', models.ManyToManyField(to='members.member')),
            ],
        ),
    ]
