# Generated by Django 5.2.16 on 2026-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_user_round_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, unique=True)),
                ('station_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTimeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_id', models.CharField(max_length=20)),
                ('goal_id', models.CharField(max_length=20)),
                ('minutes', models.IntegerField()),
            ],
            options={
                'unique_together': {('start_id', 'goal_id')},
            },
        ),
    ]
