# Generated by Django 5.2.16 on 2026-08-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_stationcache_traveltimecache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='gather_station',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='round',
            name='gather_time',
        ),
        migrations.CreateModel(
            name='DriverPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_time', models.TimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.round')),
            ],
        ),
    ]
