# Generated by Django 5.2.16 on 2026-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_gather_station_round_destination_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traveltimecache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='traveltimecache',
            name='from_time',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveltimecache',
            name='goal_time',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='traveltimecache',
            unique_together={('start_id', 'goal_id', 'goal_time')},
        ),
    ]
